title = "九龙湖行动"
author = "MaPl"
difficulty = "Easy"
flag = ["susctf{558956}", "558956"]

description = """
[公元2040年2月30日]

[中国 南京市 江宁区]


[???] 我们截获了一台外星人仿造的便携式计算终端，现在交接给你。

[???] 你的任务是破解登录这台终端所需的**个人身份识别码（PIN）**。

[???] 这台终端被设计用于支持外星间谍的渗透活动，但由于**缺乏TPM支持**只能安装 **Microsoft Windows 10** 系统。

[???] 上级情报部门指出这台机器的 PIN 很可能就是间谍使用的**银行卡密码**，找出它，帮助我们定位间谍。

[???] 为了协助你的破解任务，技术部门提取了硬盘中的**部分文件**，希望能帮到你。
"""

[attachments]
path = "附件.zip"
name = "附件.zip"
