title = "42号电台"
author = "MaPl"
difficulty = "Easy"
flag = "susctf{ssb-dtmf-224c}"

description = """
前几日我们监听到了一则通讯，并根据信号源找到了外星间谍用于远距离通讯的设备。

[通讯#03] 监听: `AD9361@OM91JV` 时间: ██████████

Por transdoni informojn en la spaco ĉirkaŭ la tero, ni uzas homan teknologion por transdoni informojn en formo de elektromagnetaj ondoj, kiuj favoras al komunikado inter ni.
"""

[attachments]
path = "task/**"
name = "task.zip"
