title = "ez_mirai"
author = "U3sug1Er1i"

difficulty = "Medium" 

flag = ["susctf{~$we_@re_a1l_viru5_d0omed_to_be_ki1l3d}", "susctf{we_@re_a1l_viru5_d0omed_to_be_ki1l3d}"]

description = """
你知道Mirai吗？Mirai是日语中"未来"一词的罗马音，但在网络病毒领域，它可是一个赫赫有名的大家族。本题附件是一个linux僵尸网络样本的压缩包，密码是"infected"，flag是针对该样本的一条攻击指令。
攻击指令的要求在你运行它的时候能看到。
注：一定要在虚拟机里运行！一定要在虚拟机里运行！一定要在虚拟机里运行！
且虚拟机运行前最好快照！！！它是个病毒（虽然windows环境中你也运行不了）
"""
[attachments]
path = "ez_mirai.zip"