title = "面向 flag 编程"
author = "MaPl"
difficulty = "Easy"
flag = "susctf{988a17fc-b28d-4af3-88e3-48d81e127ed1}"

description = """
填入正确的 `uint8_t flag[]` 即可成功编译
"""

[attachments]
path = "task.cpp"
name = "task.zip"
