title = "智子危机"
author = "MaPl"
difficulty = "Easy"
flag = "susctf{a88bd340-21f5-425e-94cc-184d9d3439da}"

description = """
研究表明，智子可以通过反复敲击NAND浮栅电容来翻转存储信息的bit位。

我们校验发现这份材料被翻转了一个bit位，导致计算机无法读取。
"""

[attachments]
path = "task.zip"
name = "task.zip"
